// <auto-generated />
using System;
using LexiQuest.Import.GoogleSheets;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LexiQuest.Import.GoogleSheets.Migrations
{
    [DbContext(typeof(GoogleImportDbContext))]
    [Migration("20240727122031_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LexiQuest.Import.GoogleSheets.ImportSaga.ImportSagaData", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Fetched")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImportSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImporterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Initialized")
                        .HasColumnType("boolean");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<bool>("SavedInPuzzleMgr")
                        .HasColumnType("boolean");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("CorrelationId");

                    b.ToTable("ImportSagaData", "googleimport");
                });

            modelBuilder.Entity("LexiQuest.Import.GoogleSheets.Model.ImportSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImporterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImportSource", "googleimport");
                });
#pragma warning restore 612, 618
        }
    }
}
